import { ArrowLeft, Shield } from "lucide-react";
import Link from "next/link";
import { ThemeSwitcher } from "@/components/theme-switcher";
import { GraduationCap } from "lucide-react";

export const metadata = {
  title: "Privacy & POPIA Notice — ACGS",
  description:
    "Learn how the AI Career Guidance System collects, uses, and protects your personal information in accordance with POPIA.",
};

export default function PrivacyPage() {
  const lastUpdated = "12 May 2026";

  return (
    <main className="min-h-screen flex flex-col items-center bg-background">
      <div className="flex-1 w-full flex flex-col items-center">
        {/* Nav */}
        <nav className="w-full flex justify-center border-b border-b-foreground/10 h-16">
          <div className="container mx-auto px-4 h-16 flex items-center justify-between">
            <a href="/">
              <div className="flex items-center gap-2">
                <div className="h-9 w-9 rounded-lg flex items-center justify-center bg-primary text-primary-foreground">
                  <GraduationCap className="h-5 w-5" />
                </div>
                <span className="text-xl font-bold">ACGS</span>
              </div>
            </a>
          </div>
        </nav>

        {/* Content */}
        <div className="container mx-auto px-4 py-10 max-w-3xl">
          <Link
            href="/"
            className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors mb-6"
          >
            <ArrowLeft className="h-4 w-4" /> Back to Home
          </Link>

          <div className="flex items-center gap-3 mb-2">
            <Shield className="h-7 w-7 text-primary" />
            <h1 className="text-3xl font-bold">Privacy &amp; POPIA Notice</h1>
          </div>
          <p className="text-sm text-muted-foreground mb-8">
            Last updated: {lastUpdated}
          </p>

          <div className="prose prose-sm dark:prose-invert max-w-none space-y-8">
            {/* 1. Introduction */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                1. Introduction
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                The AI Career Guidance System (&quot;ACGS&quot;, &quot;we&quot;,
                &quot;us&quot;, or &quot;our&quot;) is committed to protecting
                your personal information in accordance with the{" "}
                <strong>
                  Protection of Personal Information Act, 2013 (POPIA)
                </strong>{" "}
                of South Africa. This notice explains what data we collect, why
                we collect it, how we use it, and your rights as a data subject.
              </p>
            </section>

            {/* 2. What Data We Collect */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                2. What Data We Collect
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                When you use the ACGS platform, we may collect the following
                personal information:
              </p>
              <div className="bg-card rounded-xl p-5 card-shadow space-y-3">
                {[
                  {
                    label: "Account Information",
                    detail:
                      "Email address and authentication credentials provided during sign-up.",
                  },
                  {
                    label: "Academic Results",
                    detail:
                      "Subject names and percentage scores extracted from uploaded academic reports (PDF documents).",
                  },
                  {
                    label: "Skills",
                    detail:
                      "Self-reported skills selected during the career assessment.",
                  },
                  {
                    label: "Interests",
                    detail:
                      "Career interest areas chosen during the assessment process.",
                  },
                  {
                    label: "Personality Traits",
                    detail:
                      "Self-reported personality traits selected during the assessment.",
                  },
                  {
                    label: "AI Recommendations",
                    detail:
                      "Career recommendations, confidence scores, and insights generated by the AI engine based on your inputs.",
                  },
                  {
                    label: "Feedback",
                    detail:
                      "Optional ratings and comments you provide on career recommendations.",
                  },
                  {
                    label: "Saved Careers",
                    detail:
                      "Career selections you choose to bookmark for later reference.",
                  },
                ].map((item) => (
                  <div key={item.label} className="flex items-start gap-3">
                    <div className="h-2 w-2 rounded-full bg-primary mt-1.5 shrink-0" />
                    <div>
                      <span className="font-medium text-foreground">
                        {item.label}:
                      </span>{" "}
                      <span className="text-muted-foreground">
                        {item.detail}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* 3. Why We Collect This Data */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                3. Purpose of Data Collection
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                We collect and process your personal information for the
                following purposes:
              </p>
              <div className="grid gap-3 sm:grid-cols-2">
                {[
                  {
                    title: "Career Recommendations",
                    desc: "To generate personalised career guidance based on your academic profile, skills, interests, and personality.",
                  },
                  {
                    title: "Assessment History",
                    desc: "To allow you to review and compare past assessment results over time.",
                  },
                  {
                    title: "Service Improvement",
                    desc: "To use aggregated, anonymised feedback to improve the accuracy and relevance of recommendations.",
                  },
                  {
                    title: "User Experience",
                    desc: "To save your preferences and provide a seamless, personalised experience across sessions.",
                  },
                ].map((item) => (
                  <div
                    key={item.title}
                    className="bg-card rounded-lg p-4 border border-border"
                  >
                    <h4 className="font-medium text-foreground text-sm mb-1">
                      {item.title}
                    </h4>
                    <p className="text-xs text-muted-foreground">
                      {item.desc}
                    </p>
                  </div>
                ))}
              </div>
            </section>

            {/* 4. Legal Basis */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                4. Legal Basis for Processing
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                Under POPIA, we process your personal information based on your{" "}
                <strong>voluntary consent</strong>, which you provide when you
                create an account and use the platform. You may withdraw consent
                at any time by deleting your account or contacting us directly.
                Processing is also justified under POPIA Section 11(1)(a) —
                consent of the data subject.
              </p>
            </section>

            {/* 5. Data Retention */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                5. Data Retention
              </h2>
              <div className="bg-card rounded-xl p-5 card-shadow">
                <p className="text-muted-foreground leading-relaxed mb-3">
                  We retain your personal information only for as long as is
                  necessary to fulfil the purposes outlined in this notice:
                </p>
                <div className="space-y-2">
                  {[
                    {
                      data: "Account data",
                      period:
                        "Retained for the duration of your active account. Deleted upon account deletion request.",
                    },
                    {
                      data: "Assessment history",
                      period:
                        "Retained for up to 24 months from the date of creation to allow historical comparisons.",
                    },
                    {
                      data: "Uploaded documents",
                      period:
                        "Processed in-memory only. PDF files are not permanently stored on our servers; they are analysed and discarded immediately.",
                    },
                    {
                      data: "Feedback & saved careers",
                      period:
                        "Retained for the duration of your active account.",
                    },
                  ].map((item) => (
                    <div
                      key={item.data}
                      className="flex items-start gap-3 text-sm"
                    >
                      <span className="font-medium text-foreground whitespace-nowrap min-w-[140px]">
                        {item.data}
                      </span>
                      <span className="text-muted-foreground">
                        {item.period}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* 6. Data Sharing */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                6. Data Sharing &amp; Third Parties
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                We do not sell your personal information. Your data may be
                processed by the following third-party services solely for the
                purposes described above:
              </p>
              <ul className="space-y-1.5 text-sm text-muted-foreground">
                <li className="flex items-start gap-2">
                  <span className="text-primary font-bold">•</span>
                  <span>
                    <strong>Supabase</strong> — Secure database hosting and
                    authentication (data stored in compliance with applicable
                    regulations).
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary font-bold">•</span>
                  <span>
                    <strong>Google Gemini AI</strong> — Document analysis for
                    extracting academic results from uploaded PDFs. Document
                    content is sent securely and is not retained by the AI
                    provider beyond the processing session.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary font-bold">•</span>
                  <span>
                    <strong>ACGS AI Engine</strong> — Career recommendation
                    processing based on your assessment inputs.
                  </span>
                </li>
              </ul>
            </section>

            {/* 7. Your Rights */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                7. Your Rights Under POPIA
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                As a data subject, you have the following rights:
              </p>
              <div className="grid gap-2">
                {[
                  {
                    right: "Access",
                    desc: "Request a copy of the personal information we hold about you.",
                  },
                  {
                    right: "Correction",
                    desc: "Request that inaccurate or incomplete information be corrected.",
                  },
                  {
                    right: "Deletion",
                    desc: "Request that your personal information be deleted, subject to legal retention requirements.",
                  },
                  {
                    right: "Objection",
                    desc: "Object to the processing of your personal information on reasonable grounds.",
                  },
                  {
                    right: "Withdrawal of Consent",
                    desc: "Withdraw your consent at any time, without affecting the lawfulness of prior processing.",
                  },
                  {
                    right: "Complaint",
                    desc: "Lodge a complaint with the Information Regulator of South Africa.",
                  },
                ].map((item) => (
                  <div
                    key={item.right}
                    className="flex items-start gap-3 text-sm bg-muted/30 rounded-lg px-4 py-2.5"
                  >
                    <span className="font-semibold text-foreground min-w-[120px]">
                      {item.right}
                    </span>
                    <span className="text-muted-foreground">{item.desc}</span>
                  </div>
                ))}
              </div>
            </section>

            {/* 8. Disclaimer */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                8. Advisory Disclaimer
              </h2>
              <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-5">
                <p className="text-sm text-foreground leading-relaxed">
                  <strong>Important:</strong> The career recommendations
                  provided by the AI Career Guidance System are{" "}
                  <strong>advisory in nature only</strong> and do not constitute
                  guaranteed employment outcomes, guaranteed salary figures, or
                  professional career counselling. Recommendations are generated
                  by artificial intelligence based on the information you
                  provide, and may not account for all relevant personal,
                  economic, or industry-specific factors. Users are strongly
                  encouraged to consult with qualified career counsellors,
                  educators, and industry professionals before making any
                  career-related decisions. The ACGS platform and its operators
                  accept no liability for decisions made based on the
                  recommendations provided.
                </p>
              </div>
            </section>

            {/* 9. Security */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                9. Security Measures
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                We implement appropriate technical and organisational measures to
                protect your personal information, including encrypted data
                transmission (HTTPS/TLS), secure authentication via Supabase
                Auth, Row-Level Security policies on all database tables, and
                server-side API key management. While we take reasonable steps to
                safeguard your data, no system is completely immune to security
                risks.
              </p>
            </section>

            {/* 10. Contact */}
            <section>
              <h2 className="text-xl font-semibold mb-3 text-foreground">
                10. Contact Information
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                If you have any questions about this privacy notice, wish to
                exercise your rights, or have concerns about how your data is
                handled, please contact us:
              </p>
              <div className="bg-card rounded-xl p-5 card-shadow text-sm">
                <p className="text-foreground font-medium">
                  AI Career Guidance System (ACGS)
                </p>
                <p className="text-muted-foreground mt-1">
                  Email: privacy@acgs.co.za
                </p>
                <p className="text-muted-foreground mt-3 text-xs">
                  You may also lodge a complaint with the{" "}
                  <strong>Information Regulator of South Africa</strong> at{" "}
                  <a
                    href="https://inforegulator.org.za"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary hover:underline"
                  >
                    inforegulator.org.za
                  </a>
                </p>
              </div>
            </section>
          </div>
        </div>

        {/* Footer */}
        <footer className="w-full flex items-center justify-center border-t mx-auto text-center text-xs gap-8 py-16">
          <p>
            © 2026 AI Career Guidance System. Helping learners make informed
            career decisions.
          </p>
          <ThemeSwitcher />
        </footer>
      </div>
    </main>
  );
}
